= Data processing and quality

[NOTE.objectives]
====
In this module, you will learn how to determine if data is fit for your purpose and how reviewing GBIF data quality issues and flags can help you to process the data you are using for your research.
====

== Determining fitness for use and evaluating data quality

Almost always you will want to post-process your GBIF download in some way to fit your purposes. 
Sometimes you will have to make difficult judgement calls for your particular use case. 
Whenever you are dealing with thousands or millions of records, you will never quite know the true quality of the source data. 
It is important to keep in mind that you are mitigating data quality issues, not eliminating them. 

The data that we get in GBIF download, will contain data from a range of sources and the data will likely vary in its correctness and consistency. 
Correctness and consistency are two ways of documenting data errors and are measures of data quality. 
These are measures of how well the data gatherer was able to capture the true value being investigated. 
The nature of GBIF's data publication workflow means that the correctness and consistency of the data can vary dependent on the data publishers and the source of the data.
Knowing these properties of the data you have, will help you to understand the ways in which you can and cannot clean, validate and process the data.

[NOTE.presentation]
====
In this video (12:26), you will review some of the principles of data quality and fitness for use. If you are unable to watch the embedded YouTube video, you can download it locally on the xref:downloads.adoc[Files for download] page.

[.responsive-video]
video::5o7TcS2K7Cw[youtube]
====
