= Course description

== Topics

[NOTE.description]
====
* Using GBIF-mediated data for biodiversity research
* Searching GBIF.org
* Examining the data quality of a dataset
* Using the GBIF API
* Using rGBIF

This course is comprised of videos and documentation paired with quizzes and practical exercises. 
====

== Audience

[NOTE.trainers]
====
This course is designed for individuals who work as researchers or technicians in biodiversity research or policy institutions. The instruction provided is particularly useful for those who have a need or desire to use GBIF-mediated data in their own research or analyses.
====
  
== Prerequisites

[NOTE.prep]
====
* https://docs.gbif.org/course-introduction-to-gbif[Introduction to GBIF course^]

Additionally, individuals completing this course should possess the following skills and knowledge:

* Basic skills in computer and internet use, and, in particular, in the use of spreadsheets.
* Basic understanding of computer-based geographical and statistical analysis tools e.g. GIS and R, and may have already run analyses using these tools.
* Basic knowledge about geography and biodiversity informatics: geography and mapping concepts, basic taxonomy and nomenclature rules.
* A good command of English. While efforts are made to provide materials in other languages, instruction/videos will be in English.
====

// == Learning objectives

// Individuals that complete this course are ...
  
// inlude if needed, otherwise remove
// == Certificate of completion

// Upon successful submission of exercises, attendance of live sessions, and interaction with peer groups, participants have the opportunity to receive a completion certification.
