= Files for download

All files for the course may be downloaded from this page. 
Or if you prefer, all files are linked individually throughout the course as they occur in the curriculum. 
The video files are embedded throughout the course, as well, and play from YouTube or Vimeo. Subtitles are available when playing from YouTube and Vimeo for most videos. 
If you have difficulty accessing the embedded videos, please download the mp4 files to play them locally on your computer.

== Videos

The videos are narrated in English. Subtitles are not available for the downloaded videos.

xref:attachment$gbif_species_search.mp4[GBIF species search] (23 MB)

xref:attachment$gbif_occurrence_search.mp4[GBIF occurrence search] (40.7 MB)

xref:attachment$gbif_spatial_search.mp4[GBIF spatial search] (14.8 MB)

xref:attachment$gbif-api-intro-marie.mp4[Introduction to the GBIF API] (51.8 MB)

xref:attachment$species-matching-tool-marie.mp4[GBIF species matching tool] (7.2 MB)

xref:attachment$rgbif-intro-john.mp4[Introduction to rgbif] (91.3 MB)

== Exercise sheets

There are 5 exercise sheets for this course. 
They are Microsoft Word documents. The exercises sheets are written in English and should be completed in English.

** xref:attachment$Ex1_Darwin_Core.docx[Download Exercise 1] (MS Word 152 KB)

** xref:attachment$Ex2-Search-gbif.docx[Download Exercise 2] (MS Word 7 KB)

** xref:attachment$Ex3-data-quality.docx[Download Exercise 3] (MS Word 7 KB)

** xref:attachment$Ex4-species-api.docx[Download Exercise 4] (MS Word 7 KB)

** xref:attachment$Ex5-r-tutorial.docx[Download Exercise 5] (MS Word 8 KB)

== R file

xref:attachment$Lemur_catta_project.Rmd[Download Lemur catta script] (R script 8 KB)
