= Introduction to the GBIF API

The https://api.gbif.org/[GBIF API^] was developed to provide a programmatic way to query and publish data on GBIF.org. The API can be used to make advanced queries not supported by the website. It can also be used to include the results of GBIF queries in scripts, workflows or analyses which can then be repeated reliably and automatically. It can even allow GBIF data to be embedded into other websites. It can be accessed using any programming language, from a command-line terminal interface, or in some cases using a web browser.

Reference the full https://techdocs.gbif.org/en/openapi/[API documentation^] within https://techdocs.gbif.org/en/[GBIF Technical Documentation^].

[NOTE.presentation]
====
In this video (24:05), Marie Grosjean, GBIF Data Administrator, provides an introduction the GBIF API. If you are unable to watch the embedded Vimeo video, you can download it locally on the xref:downloads.adoc[Files for download] page.

[.responsive-video]
video::982612361[vimeo]
====
