= Using the GBIF data portal

== Species search

[NOTE.presentation]
====
In this video (05:01), Cecilie Svenningsen, GBIF Data Administrator, demonstrates a species search on GBIF.org. If you are unable to watch the embedded Vimeo video, you can download it locally on the xref:downloads.adoc[Files for download] page.

[.responsive-video]
video::740752435[vimeo]
====

== Occurrence search

[NOTE.presentation]
====
In this video (08:25), Cecilie Svenningsen, GBIF Data Administrator, demonstrates an occurrence search on GBIF.org. If you are unable to watch the embedded Vimeo video, you can download it locally on the xref:downloads.adoc[Files for download] page.

[.responsive-video]
video::740759609[vimeo]
====

== Spatial search

[NOTE.presentation]
====
In this video (03:38),Cecilie Svenningsen, GBIF Data Administrator, demonstrates a spatial search on GBIF.org. If you are unable to watch the embedded Vimeo video, you can download it locally on the xref:downloads.adoc[Files for download] page.

[.responsive-video]
video::740759987[vimeo]
====
