= Data processing tools

While GBIF filters will allow for some data processing i.e. select only those data for download that fulfil certain criteria, it is highly recommended that you additional data processing and a range of tools are available. 
Your choice of which tool you use will be based on personal access, familiarity and utility of each of the tools.

Examples that can be used for this are: 

* Spreadsheet editing software e.g. Excel, Google Sheets (smaller datasets)
* OpenRefine
* R packages and scripts eg rgbif, CoordinateCleaner, scrubr and biogeo (automated data processing)
* Geographical Information Systems (GIS) e.g. ArcGIS, QGIS and MapInfo

It is always important to include a data visualisation step in your data processing so that you can identify anomalous data points that may have been missed during the processing stage. 
For those processing in R, this can be done within R, however, with OpenRefine or spreadsheet editing sofware you may have to use GIS software or even tools such as Google Earth for data visualisation.
