= Terminology 

[NOTE.objectives]
This module provides an introduction to the language, terminology and definitions for some of the basic concepts, functions and processes related to biodiversity data mobilization.

== Definitions

[NOTE.presentation]
====
In this video (12:02), you will review terminology used in this course. 

If you are unable to watch the embedded video, you can xref:attachment$foundations-definitions_v1-720p.mp4[download,opts=download] it locally. (MP4 - 45.8 MB)
====

[.responsive-video]
video::434713168[vimeo]

== Software

[NOTE.presentation]
====
In this video (05:58), you will review examples of the different types of applications and software available in the world of biodiversity mobilization informatics. 

If you are unable to watch the embedded video, you can xref:attachment$foundations-software_v1-720p.mp4[download,opts=download] it locally. (MP4 - 23.5 MB)
====

[.responsive-video]
video::434713189[vimeo]

== Structures

[NOTE.presentation]
====
In this video (13:10), you will review the field and data types that hold data, the structures that help to organize and protect that data and what these mean for the integrity and security of your data. 

If you are unable to watch the embedded video, you can xref:attachment$foundations-structures_v1-720p.mp4[download,opts=download] it locally.  (MP4 - 44.4 MB)
====

[.responsive-video]
video::434713175[vimeo]