= Final assignments

[NOTE.assignments]
For your final activities, you will complete and submit two Use Cases for evaluation.

For each you case, there are three required files for submission:

* completed exercise sheet (MS Word Doc or similar is acceptable)
* data capture spreadsheet (MS Excel, csv, txt or similar is acceptable)
* cleaned/standardized dataset (MS Excel, csv, txt or similar is acceptable)

== Filenames

Include the use case and exercise number along with your name on all files submitted. For example:

* Russell-InvasiveSpecies-exercise-sheet.docx
* Russell-InvasiveSpecies-exercise1.xlsx
* Russell-InvasiveSpecies-exercise2.xlsx. 

IMPORTANT: All files must be submitted in *English*. Contact training@gbif.org if you have any questions.

== Assignment submission

ifdef::backend-pdf[]
Assignments can be submitted from the online (HTML) version of the course.
endif::backend-pdf[]

ifndef::backend-pdf[]
Please submit your assignment files using the form below.  If you do not see a form, you can also visit the https://gbif.app.box.com/f/1e44182c4bc74d659082c0e952d83e80[submission site^] in a new window.

++++
<iframe src="https://gbif.app.box.com/f/1e44182c4bc74d659082c0e952d83e80" style="width: 100%; min-height: 1100px;"></iframe>
++++
endif::backend-pdf[]
