= Files for download

Videos and practice files for the course may be downloaded from this page. Or if you prefer, the videos and files are linked individually throughout the course as they occur in the curriculum.

== Course videos

The videos are narrated in English. Subtitles are not available for the downloaded videos.

xref:attachment$capture-videos1.zip[capture-videos1.zip,opts=download] (60.8 MB)

xref:attachment$capture-videos2.zip[capture-videos2.zip,opts=download] (59 MB)

xref:attachment$management-videos.zip[management-videos.zip,opts=download] (63.4 MB)

xref:attachment$publishing-videos.zip[publishing-videos.zip,opts=download] (50.3 MB)

== Practice exercise data
This xref:attachment$UC-Practice-exercise-files.zip[compressed file,opts=download] (ZIP 1 MB) contains the exercise files for the Practice Use Case. 

=== Practice exercise sheet
This xref:attachment$UC-Practice-exercise-sheet_EN.docx[compressed file,opts=download] (MS Word 4 MB) contains the exercise sheet for the Practice Use Case. 
