site:
  title: Corsi di formazione GBIF
  start_page: ROOT::index.adoc
  keys:
    language: it
content:
  sources:
    - url: .
      start_path: ./it/home
      branches: HEAD
    - url: .
      start_path: ./it/intro-to-gbif
      branches: HEAD
    - url: .
      start_path: ./it/data-mobilization
      branches: HEAD
    - url: .
      start_path: ./it/data-use
      branches: HEAD
    - url: .
      start_path: ./it/dna-barcoding
      branches: HEAD
    - url: .
      start_path: ./it/nodes
      branches: HEAD
    - url: .
      start_path: ./it/epn
      branches: HEAD
    - url: .
      start_path: ./it/grscicoll
      branches: HEAD
     - url: .
      start_path: ./it/project-planning
      branches: HEAD
output:
  clean: false
  dir: ./output/it
runtime:
  fetch: true
  cache_dir: ./cache
ui:
  bundle:
    url: https://builds.gbif.org/job/tech-docs-theme/lastSuccessfulBuild/artifact/build/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental_ui
urls:
  html_extension_style: drop
  latest_version_segment_strategy: redirect:to
  latest_version_segment: latest
  redirect_facility: httpd
asciidoc:
  extensions:
  - ./lib/asciidoctor-question
  attributes:
    idprefix: ''
    idseparator: '-'
    page-pagination: yes
    page-toctitle: 'Contenuto della pagina'
    language: it
    null: ␀
antora:
  extensions:
  - require: '@antora/lunr-extension'
    index_latest_only: true
    languages: [it]
