site:
  title: GBIF Training Courses
  start_page: ROOT::index.adoc
  keys:
    language: en
content:
  sources:
    - url: .
      start_path: ./en/home
      branches: HEAD
    - url: .
      start_path: ./en/intro-to-gbif
      branches: HEAD
    - url: .
      start_path: ./en/data-mobilization
      branches: HEAD
    - url: .
      start_path: ./en/data-use
      branches: HEAD
    - url: .
      start_path: ./en/dna-barcoding
      branches: HEAD
    - url: .
      start_path: ./en/nodes
      branches: HEAD
    - url: .
      start_path: ./en/epn
      branches: HEAD
    - url: .
      start_path: ./en/grscicoll
      branches: HEAD
     - url: .
      start_path: ./en/project-planning
      branches: HEAD      
output:
  clean: false
  dir: ./output/en
runtime:
  fetch: true
  cache_dir: ./cache
ui:
  bundle:
    url: https://builds.gbif.org/job/tech-docs-theme/lastSuccessfulBuild/artifact/build/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental_ui
urls:
  html_extension_style: drop
  latest_version_segment_strategy: redirect:to
  latest_version_segment: latest
  redirect_facility: httpd
asciidoc:
  extensions:
  - ./lib/asciidoctor-question
  attributes:
    idprefix: ''
    idseparator: '-'
    page-pagination: yes
    page-toctitle: 'Page contents'
    language: en
    null: ␀
antora:
  extensions:
  - require: '@antora/lunr-extension'
    index_latest_only: true
    languages: [en]
