site:
  title: TRADITIONAL CHINESE TITLE REQUIRED GBIF培訓課程
  start_page: ROOT::index.adoc
  keys:
    language: zh-tw
content:
  sources:
    - url: .
      start_path: ./zh-tw/home
      branches: HEAD
    - url: .
      start_path: ./zh-tw/intro-to-gbif
      branches: HEAD
    - url: .
      start_path: ./zh-tw/data-mobilization
      branches: HEAD
    - url: .
      start_path: ./zh-tw/data-use
      branches: HEAD
    - url: .
      start_path: ./zh-tw/dna-barcoding
      branches: HEAD
    - url: .
      start_path: ./zh-tw/nodes
      branches: HEAD
    - url: .
      start_path: ./zh-tw/epn
      branches: HEAD
    - url: .
      start_path: ./zh-tw/grscicoll
      branches: HEAD
    - url: .
      start_path: ./zh-tw/project-planning
      branches: HEAD
    - url: .
      start_path: ./zh-tw/foundations
      branches: HEAD
output:
  clean: false
  dir: ./output/zh-tw
runtime:
  fetch: true
  cache_dir: ./cache
ui:
  bundle:
    url: https://builds.gbif.org/job/tech-docs-theme/lastSuccessfulBuild/artifact/build/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental_ui
urls:
  html_extension_style: drop
  latest_version_segment_strategy: redirect:to
  latest_version_segment: latest
  redirect_facility: httpd
asciidoc:
  extensions:
  - ./lib/asciidoctor-question
  attributes:
    idprefix: ''
    idseparator: '-'
    page-pagination: yes
    page-toctitle: 'TRADITIONAL CHINESE TRANSLATION NEEDED 頁面內容'
    language: zh-tw
    null: ␀
#Not yet supported, node required during the build.
#antora:
#  extensions:
#  - require: '@antora/lunr-extension'
#    index_latest_only: true
#    languages: [zh]
