= Communications and stakeholder engagement

== Context

[NOTE.description]
====
An introduction to developing a communication plan for engaging your node’s network.
====

== Learning objectives

[NOTE.objectives]
====
After completing this module, you should be able to perform the following:

* Describe the different types of audiences that GBIF needs to engage on the global level
* Understand that in developing a communication strategy, you need to adapt key messages to the specific audience you are engaging and select the appropriate medium
* Describe different communication means (media) that nodes can use to engage their network
* Adapt messages and media to different audiences
* Develop communication strategies tailored to specific audiences
====

== Trainers

[NOTE.trainers]
====
The following trainers have developed the content for this topic:

* Anabela Plos, Argentina
* Carole Sinou, Canadensys
* Pierre Radji, Togo

with additional contributions from:

* Cristina Villaverde, Spain
* Dairo Escobar, Colombia
* Luke Jimu, Zimbabwe

GBIF staff consultant: Mélianie Raymond, Community and Capacity Manager
====

== GBIF's communication strategy

[NOTE.presentation]
====
An introduction to the key audiences, communication needs and key messages in the GBIF communication strategy.  
====

&nbsp;

++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vRTtBeifC9ez3guNXtZF-uth2TiA0RyXPMvMJ1gVBDXa_lZFGsdiMxhiMxEklSHNT4UNApEvpxs0ZPH/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++

&nbsp;

== Communication and stakeholder engagement at the node level

[NOTE.presentation]
====
Nodes managers present on how to develop communications plans to assist them in engaging their key audiences.
====

&nbsp;

++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vSRyc0ipKJPqNUEQGWxLBoSJ7cgCA7kDyfq39Wv34OeHSDBYQhJ3yPY7ZurP7RdG-_EB7pc12s17ZA9/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++

&nbsp;

=== Experiences from Spain and Zimbabwe

&nbsp;

++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vS0TZkKNG-74RKE6_4d_gFQwMrh89lKyA2_hFo5hZe7x4IzBC_jwEMwh8fQosmGKMdO1QDlrCTHrJz4/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++

&nbsp;

=== Experiences from Togo

&nbsp;

++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vTX9heOoz2WIjjqfQuXGDJqfJhPqp6uvifaIZs25C1hmbKUBPqeW4cfW-Y8HY1qZ1IX7v11JaP8T0wO/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++

&nbsp;

=== Experiences from Colombia

&nbsp;

++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vQwbsWbD-SgfXFNbbN3MksoRr-c1rpwhqbWhnhXKjbExNTomvTwf5CVtoaP5UN7hf8-RowKaOO6V6g0/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++

&nbsp;

== Exercises

=== Engaging key audiences exercise 

[NOTE.activity]
====
For this activity, Nodes will collect success stories on engaging key audiences across the nodes community.
====

&nbsp;

++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vSK5xcjs_kMzNySH41n27RmzMJsqaroQ6KpDjDqbQbsnJ2bHm3XIRdYt0d_HyY5PevaKvLzy1oNQBSC/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++

&nbsp;

=== Communication for stakeholder engagement exercise

[NOTE.activity]
====
For this activity, you will work in pairs to design a communications approach for engaging a specific audience and practice delivering your key messages in sharing your approach back to your group.
====

&nbsp;

++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vTDzUMaDXOM4OOMaPkNoqCcTzNRaZP16TfrvLTDvo9GHxpwCdGM_rJP7RRWTz3cHVlpawts8z6e04X_/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++

&nbsp;
