= Developing training for your network

== Context

[NOTE.description]
====
Overview on how to strengthen the capacity of node stakeholders by developing a strategic training plan, how to plan and organize a training, and requirements for an effective training. Will include the GBIF Secretariat training approach and guidance for nodes on training materials available for reuse.
====

== Learning objectives

[NOTE.objectives]
====
After completing this module, you should be able to perform the following:

* Describe key training audiences
* Describe training delivery methods
* Develop a training approach
* Develop curriculum and materials
* Plan and implement training
====

== Trainers

[NOTE.trainers]
====
The following trainers have developed the content for this topic:

* Anabela Plos, Argentina
* Carole Sinou, Canadensys
* Fatima Parker-Allie, South Africa

with additional contributions from:

* Christian Elleran, ASEAN Center for Biodiversity
* Dag Endresen, Norway
* Jean Ganglo, Benin
* Oleg Borodin, Belarus
* Piotr Tykarsky, Poland

GBIF staff consultant: Laura Anne Russell, Training Officer for Community and Capacity
====

== Using training to strengthen a node's stakeholder community

[NOTE.presentation]
====
Overview on how to strengthen the capacity of node stakeholders by developing a strategic training plan, how to  plan and organize a training, and requirements for an effective training. Will include the GBIF Secretariat training  approach and guidance for nodes on training materials available for reuse.  
====

&nbsp;

++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vQonV5a_hh4PxdJNzlarC4DO4y0KPUspy6TkX139jgidQhRwZp3RF30-UQ9P4zmjOtKQpr2KDBB0Rpx/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++

&nbsp;

== Developing and implementing training for your network

[NOTE.presentation]
====
Nodes managers present on how they developed and and implemented training for their networks
====

=== Experiences from ASEAN Network

&nbsp;

++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vTXB1JHlEtEM8rpYiWtNxLnucQ3VVpQ2bKwWG1P_UUUnh-hF_OcE-XTpB33NPa5hWJ0UmOFxzJ3iKr4/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++

&nbsp;

=== Experiences from the Benin Masters programme

&nbsp;

++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vTnL68wD0U50-Yd89kshpG95chla1PfQn_YtV9JWpx_zoGVnCONZYlzv4pidVbGwDlXK7-NC8Td75Nw/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++

&nbsp;

=== Experiences from the BioDATA programme

&nbsp;

++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vT4rgWaXRSN3hH580fgK2CQcV6yQzDlGkkYrmCzlx79cas6ZgYwprbuwvYwRJ6Bjq7Y5Fd38zJjh-6R/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++

&nbsp;

== Exercises

=== Developing a training strategy exercise 

[NOTE.activity]
====
Individual and group activity to develop a training strategy. Consider in what ways you need to enhance your nodes community and where the priority falls in your overall strategic plan.
====

&nbsp;

++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vS_2lkUg5Ft0F3mE18HHy8inc0lLreSCK4kf94YmxeR812WSWVPgEo3VcbDN7EgldgcVvh5Kpkcdv6M/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++

&nbsp;

=== Developing and implementing training exercise

[NOTE.activity]
====
Group activity building on the previous exercise to develop and implement a training. Time will be allotted to determine all the practicalities and then to present to others for feedback.
====

&nbsp;

++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vSqH5vmeX313PlsjU_EXcrfA5ww7IAoANTXvYK0Sus_vZ-d8qCSyxn7znzn3WP-CxctJb4eBvn1AK6c/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++

&nbsp;
