= Resourcing and collaborative projects

== Context

[NOTE.description]
====
...
====

== Learning objectives

[NOTE.objectives]
====
After completing this module, you should be able to perform the following:

* Describe node funding mechanisms
* Describe 
====

== Trainers

[NOTE.trainers]
====
The following trainers have developed the content for this topic:

* Anders Telenius, Sweden

with additional contributions from:

* André Heughebaert, Belgium
* Anne-Sophie Archambeau, France
* Jean Paul Kubwimana, ARCOS

GBIF staff consultant: Maheva Bagard Laursen, Programme Officer for Community and Capacity
====

== Models for resourcing nodes activities

[NOTE.presentation]
====
...  
====

== Experiences from ARCOS

&nbsp;

++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vQyAq52I26pvnAd3CO1zq8TClfrmFM7lKulTfmjcalGmoSb3bJLUUyA3bDZzI-YeMZey8dU_v50t4YV/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++

&nbsp;

=== Experiences from Sweden

&nbsp;

++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vRZGmPdKjR0jhUWFJBN1_H6shg54f2Bo3ogST8K0bFDGzjHl1Z_aT4inBlyNIJp6LzH58C31zwar7PF/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++

&nbsp;

=== Experiences from Belgium

&nbsp;

++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vQ4fOlQ84WEz9urdx6tuh8IpaayrD9m0ximlDE2YhsitjGuQzN9k7SN8eOy_yUhuSu59veqUgfqRKk0/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++

&nbsp;

=== Nodes resourcing exercise 

[NOTE.activity]
====
Overview of resourcing in the community and speed dating activity - short exchanges with other node managers on  the topic of resourcing for node activities and aiming to capture tips and recommendations.
====

&nbsp;

++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vS-X7saEvVOR1sctblUx9ataD5W_ey2gOX4S8WZNiiFsSldgc8ulWThXT5BzcC19cRvw-baP3sf3HyW/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++

&nbsp;

== GBIF support to collaborative projects

[NOTE.presentation]
====
An introduction to collaboration in the community with an overview of the different programmes supported by the  GBIF Secretariat and nodes.
====

&nbsp;

++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vQ3GFcDFbGGhUR6xjsC_FCE9Yp9iN2rIxB_zr4hPITyPR2QYEWKpHVDZi7K8BTZorK-NQdiumWSlQmJ/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++

&nbsp;

=== Experiences from France

[NOTE.presentation]
====
There are many ways nodes can get involved in supporting collaborative projects, from leading projects, partnering  in them, providing mentoring support, assisting as trainers, supporting assessment and reporting processes.
====

&nbsp;

++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vSBkvQV1d6el4oKEdBT40vcIA2yRSJKdw0duyGDdriv2mlGnKLUT-3OEhIk4sWImEiwtZloFmU__OAk/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++

&nbsp;

=== Project assessment exercise

[NOTE.activity]
====
For this activity, we will split into groups focused on one of three typical project types: mentoring projects, data mobilization projects and regional events. Each group will firstly take on the role of assessing fictitious concept notes and then work on developing a full proposal.
====

&nbsp;

++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vQxQR_ViMHbmSRDPEgz6FlwY_mNn9jBSg3jL9MWeE5PDeXIJ5KNgbxBNdB0gPhtAwzCQMrijrM_XepK/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++

&nbsp;
