= Resourcing and collaborative projects

== Context

[NOTE.description]
====
There is huge variety in the ways that nodes' resource their activities. Most nodes combine sources of funding and institutional support to deliver their work programmes. 
Not only newly established nodes need to consider how to make the case for funding their activities, and there is much we can learn from sharing experiences on this topic. Many nodes have success stories to share in designing and implementing funded projects based on collaborative actions with other nodes in the network. These projects are essential in strengthening the nodes community. In this module, nodes will share their experiences, tips and recommendations for resourcing their activities, as well as working in groups to consider how to design three typical collaborative project types: mentoring actions, regional events and data mobilization projects. 

These materials were developed as part of the 2019 Global Nodes training in Leiden, Netherlands.
====

== Learning objectives

[NOTE.objectives]
====
After completing this module, you should be able to perform the following:

* Describe node funding mechanisms
* Describe 
====

== Trainers

[NOTE.trainers]
====
The following trainers have developed the content for this topic:

* Anders Telenius, Sweden
* Liam Lysaght, Ireland
* Pierre Radji, Togo

with additional contributions from:

* André Heughebaert, Belgium
* Anne-Sophie Archambeau, France
* Jean Ganglo, Benin
* Jean Paul Kubwimana, ARCOS

GBIF staff consultant: Maheva Bagard Laursen, Programme Officer for Community and Capacity
====

== Models for resourcing nodes activities

[NOTE.presentation]
====
Nodes managers share their experiences with resourcing their node activities.   
====

=== Experiences from ARCOS

&nbsp;

++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vQyAq52I26pvnAd3CO1zq8TClfrmFM7lKulTfmjcalGmoSb3bJLUUyA3bDZzI-YeMZey8dU_v50t4YV/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++

&nbsp;

=== Experiences from Sweden

&nbsp;

++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vRZGmPdKjR0jhUWFJBN1_H6shg54f2Bo3ogST8K0bFDGzjHl1Z_aT4inBlyNIJp6LzH58C31zwar7PF/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++

&nbsp;

=== Experiences from Belgium

&nbsp;

++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vQ4fOlQ84WEz9urdx6tuh8IpaayrD9m0ximlDE2YhsitjGuQzN9k7SN8eOy_yUhuSu59veqUgfqRKk0/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++

&nbsp;

== GBIF support to collaborative projects

[NOTE.presentation]
====
An introduction to collaboration in the community with an overview of the different programmes supported by the  GBIF Secretariat and nodes.
====

&nbsp;

++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vQ3GFcDFbGGhUR6xjsC_FCE9Yp9iN2rIxB_zr4hPITyPR2QYEWKpHVDZi7K8BTZorK-NQdiumWSlQmJ/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++

&nbsp;

=== Experiences from France

[NOTE.presentation]
====
There are many ways nodes can get involved in supporting collaborative projects, from leading projects, partnering  in them, providing mentoring support, assisting as trainers, supporting assessment and reporting processes.
====

&nbsp;

++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vSBkvQV1d6el4oKEdBT40vcIA2yRSJKdw0duyGDdriv2mlGnKLUT-3OEhIk4sWImEiwtZloFmU__OAk/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++

&nbsp;

== Exercises

=== Nodes resourcing exercise 

[NOTE.activity]
====
Overview of resourcing in the community and speed dating activity - short exchanges with other node managers on  the topic of resourcing for node activities and aiming to capture tips and recommendations.
====

&nbsp;

++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vS-X7saEvVOR1sctblUx9ataD5W_ey2gOX4S8WZNiiFsSldgc8ulWThXT5BzcC19cRvw-baP3sf3HyW/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++

&nbsp;

=== Project assessment exercise

[NOTE.activity]
====
For this activity, we will split into groups focused on one of three typical project types: mentoring projects, data mobilization projects and regional events. Each group will firstly take on the role of assessing fictitious concept notes and then work on developing a full proposal.
====

&nbsp;

++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vQxQR_ViMHbmSRDPEgz6FlwY_mNn9jBSg3jL9MWeE5PDeXIJ5KNgbxBNdB0gPhtAwzCQMrijrM_XepK/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++

&nbsp;

=== Ficticious calls and concept notes

*PDF downloads*

xref:attachment$2019_GBIF_CESP_Call_for_Proposals.pdf[Ficticious CESP Call for Proposal]

xref:attachment$FictitiouMentoringConceptNote.pdf[Ficticious mentoring concept note]

xref:attachment$FictitiousRegionalEventConceptNote.pdf[Ficticious regional event concept note]

xref:attachment$GlBiInF4_call_print.pdf[Ficticious GlBiInF call for proposal]

xref:attachment$FictitiousDataMobilizationConceptNote.pdf[Ficticious data mobilization concept note]
