= Strategic planning

== Context

[NOTE.description]
====
An introduction to developing strategic plans at the node level and aligning these with the GBIF strategic plan.
====

== Learning objectives

[NOTE.objectives]
====
After completing this module, you should be able to perform the following:

* Understand the purpose of strategic planning.
* Understand GBIF's strategic planning process and how nodes contribute to it.
* Understand the role of nodes in implementing GBIF's strategy.
* Develop a strategy to engage the business sector in the data mobilization process.
====

== Trainers

[NOTE.trainers]
====
The following trainers have developed the content for this topic:

* Anders Telenius, Sweden
* Fatima Parker-Allie, South Africa
* Liam Lysaght, Ireland

GBIF staff consultant: Joe Miller, Executive Secretary
====

== GBIF strategic planning

[NOTE.presentation]
====
An introduction to GBIF’s current strategic plan and community involvement in the development of our next plan.  
====

&nbsp;

++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vTAiUOB8Q22GI_GuWufTCfx-54OWXzXxxS_P_jlrtIeBas6wbEELpTxYfWeYYI59v7mMboEvkcee7nW/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++

&nbsp;

=== Nodes contributions to the GBIF strategic plan

[NOTE.activity]
====
For this activity, Nodes will be asked to come up with ideas in response to the question: 

What will be the main contribution of nodes to GBIF’s next strategic period?

They should first come up with an idea on their own, then in a pair, then in a group of four.

Each group of four will be asked to come up with their best idea to present to the whole room in a facilitated summary of the ideas.
====

&nbsp;

++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vRSJIq2ohvAPSvS5iPwYvBeF_FYhydOM85MBTjkJ7qq6WRz_tWkm5uNcIu4ZGjpzFpjiSl4vp5A92Kg/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++

&nbsp;

== Strategic planning at the node level

[NOTE.presentation]
====
Nodes managers present on how nodes have developed their strategic plans and how these relate to the GBIF strategic plan.
====

=== Experiences from Ireland

&nbsp;

++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vTdYcqzl_V8A9RkDXv-ebRELoRlRatGwsW6tXub7K9aBygzTMLFZ6ZJ0ffdeeZy8i5uwZ0hTCizZVJK/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++

&nbsp;

=== Experiences from Sweden

&nbsp;

++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vSc69uoytBlvOCFY7A0Bh3p0JmEtFrJxhguVr_CtXuLn3c_kdtuC8fWrz5Fel6waOLkqXJ-Sj5R5eNP/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++

&nbsp;

=== Experiences from South Africa

&nbsp;

++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vTF3fB-XHQzYF2LeziPGm-ceIRXQZqJtI2g4ECVQW2Yv3HDFY85WHz5uRU-2_SfuYG012VIkdX5RpxJ/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++

&nbsp;

=== Develop new ideas for your node's strategic plan

[NOTE.activity]
====
For this activity, you will work in pairs to develop new ideas for your node's next strategic plan. 

Practice presenting these ideas to your group for feedback.
====

&nbsp;

++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vTztQ59LYHU-RZXJSVubqLisbfzcsxAH_DZ9iP_CDC96ZoUOb0SLcd54TUz05APhMOcfXGBPYUO2rXa/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++

&nbsp;
