= Assignment
[NOTE.assignments]

== Instructions
You are preparing to complete the dataset deliverables section of your full proposal: 

* Choose one of your project datasets and provide the following required information.
* List any questions or uncertainties you encounter while completing this exercise that you would like to discuss during Module 3.

. Dataset title 
.. Choose an informative title that reflects the dataset's content
. Most relevant dataset type  for your data 
.. Description of biodiversity data holding (metadata-only dataset), 
.. Species or taxon lists (checklists), 
.. Occurrences (occurrences dataset), 
.. Sampling-events, survey, monitoring (sampling event dataset). 
. Approximate # of records 
.. Estimate how many records the dataset will include
. Current data format 
.. Are your data undigitized, partially digitized, digitized?
. Scope of the dataset
.. Geographic scope: Be specific (e.g., "Ouémé classified forest in Center Benin, West Africa.")
.. Temporal scope: Time period covered (e.g., "February 3, 2014 - December 27, 2016")
.. Taxonomic scope: Species or groups included (e.g., "Fabaceae, Ochnaceae, Bignoniaceae, Loganiaceae, Combretaceae, Rubiaceae, Sapotaceae, Chrysobalanaceae, Meliaceae, Celastraceae, Anacardiaceae, Araliaceae")
. Sampling methodology - only for Sampling-events, survey, monitoring (sampling event dataset)
.. Description of the sampling method used to collect the data
. Relevance
.. Why does the sharing of the data included in this dataset contribute to address regional needs and/or priorities identified in your project proposal?
.. Why is the dataset type selected the most relevant to share the data?
. Data holder(s)
.. Who currently owns the data?
.. Do you have their permission to share it openly through GBIF? 
. Expected publication date of the dataset 
.. Consider the time and resources needed to secure permissions, standardize the data and publish your dataset