= Biodiversity data mobilization project planning

== Description

[NOTE.description]
====
This course aims to provide Biodiversity Information for Development (BID) programme applicants with the knowledge needed to develop a realistic, coherent and well-designed data mobilization plan as part of their project proposal.
 
This course consists of videos and documentation paired with quizzes and practical exercises.
====

== Audience

[NOTE.trainers]
====
This course is designed for BID programme applicants who have advanced to the full proposal phase. 
====
  
== Prerequisites

[NOTE.prep]
====
* https://docs.gbif.org/course-introduction-to-gbif[Introduction to GBIF course^]

Additionally, individuals completing this course should possess the following skills and knowledge:

* A good command of English. While efforts are made to provide materials in other languages, instruction/videos will be in English.
====

== Certificate of completion

[NOTE.complete]
====
Upon successful attendance of live sessions and completion of activities, participants will receive a completion certification.
====
