= Biodiversity data mobilization project planning

== Description

[NOTE.description]
====
This course consists of videos and documentation paired with quizzes and practical exercises and aims to provide https://www.gbif.org/bid[Biodiversity Information for Development^] (BID) programme applicants with the knowledge needed to develop a realistic, coherent and well-designed data mobilization plan as part of their project proposal.

This course will not cover all aspects of project planning and management, but rather focus on the specifics related to managing a project aiming to mobilize data through GBIF.

=== Topics

* Assessing goals and defining deliverables
* Measuring progress
* Documenting a full proposal
====

== Audience

[NOTE.trainers]
====
This course is designed for BID programme applicants who have advanced to the full proposal phase. 
====
  
== Prerequisites

[NOTE.prep]
====
* A BID programme project advanced to the full proposal phase
* Individuals completing this course should have a good command of English. While efforts are made to provide materials in other languages, instruction/videos will be in English.
====

[NOTE]
If you need to learn more about GBIF in advance of the course, it is recommended to complete the https://docs.gbif.org/course-introduction-to-gbif[Introduction to GBIF course^].

== Certificate of completion

[NOTE.complete]
====
Upon successful attendance of live sessions and completion of activities, participants will receive a completion certification.
====