= Module 3: Documenting a full proposal

== Learning objectives

[NOTE.objectives]
====
This module provides a demonstration of working in the GBIF Grants Portal on a BID Full Proposal

After completing this module, you should be able to perform the following:

* Understand the elements in a dataset deliverable
* Develop a dataset deliverable

====

== Presentation

[NOTE.presentation]
====
This video demonstrates how to add a dataset deliverable in a BID full proposal.

&nbsp;

[.responsive-video]
video::1109755110[vimeo]
====

== Example of a dataset deliverable

This example is largely based on a real dataset (DOI: https://doi.org/10.15468/viradl[10.15468/viradl^]), but includes fictional elements to illustrate key concepts

*Dataset Title* 

Solomon Islands Community Seagrass & Dugong Conservation Data (2018-2024)
 
*Dataset Type*

Sampling-events, survey, monitoring

*Approximate # of Records*

1500

*Current Format of the data (i.e., undigitized, partially digitized, digitized)*

Partially digitized (Data up to 2022 have been digitized, however, data collected in 2023 and 2024 are still in paper form in field notebooks).

*Geographic Scope*

Tetepare island (Western Province), Kmaga (Isable Province) and Marau (Guadalcanal Province)

*Temporal Scope*

15 January 2018 to 31 January 2024

*Taxonomic Scope*

Cymodocea rotundata, Cymodocea serulata, Enhalus acoroides, Halodule uninervis, Halophila Ovalis, Syringodium Isoetifolium, Thalassia hemprichii, Thalassoden Ciliatum, Zostera Capricorni

*Sampling Methodology (if relevant)*

Annual survey using 50 m fixed transect and standardized checklists to record seagrass and dugong occurrences and associated observations.

*Relevance [why this dataset?]*

The publication of this dataset will highlight the impact of community-based conservation efforts. It will also support Target 8 of the GBF by contributing to efforts to minimize the impact of climate change on biodiversity and build resilience, and promote the role of Locally Managed Marine Areas, a national priority identified in the Solomon Islands’ National Biodiversity Strategy and Action Plan (NBSAP). By publishing this dataset as a sampling event, it will enable the sharing of information on the relative abundance of species over time.

*Data Holders*

Solomon Islands Ministry of the Environment and Climate Change

*Has the data holder confirmed agreement to publish the data through GBIF?*

Yes

*Expected Publication date*

25 June 2026
