= Exercise - Budget details
[NOTE.assignments]

== Instructions
You are preparing to complete the budget details section of your full proposal. List any questions or uncertainties you encounter while completing this exercise that you would like to discuss during Module 3.

Choose one of your project activities that requires a budget and provide the following  information:

. Activity 
.. Select the *activity* related to the budget item. Note: activities are added in the Activities and deliverables section of the full proposal.
. Type
.. Select the *type of cost*
... Consumables or general purchases
... IT purchases
... Salary
... Travel  
. Title 
.. The Title should make it easy to identify the specific cost. For example, if the expense Type is ‘Conference Logistics’ the Title might be ‘Venue hire’ or ‘Catering’.
. Explanation 
.. Explain how you came to the amount and add enough details to make it clear what it covers (e.g. unit cost x quantity or daily rate x number of days).
. Requested amount
.. The amount required for the budget item.
. Co-funding
.. List any co-funding provided for the budget item.

Repeat as many times as necessary to detail the budget items for the activity.

[IMPORTANT] 
.Unallowable expenses
==== 
GBIF Grant funds cannot be used for the following types of expenses:

* Overhead costs not directly tied to project activities
* Bank fees, postal or courier costs
* Exchange rate losses
* Reimbursable taxes (must confirm tax status if invited to submit a full proposal)
* Fieldwork or collection of new field data
* Laboratory research for new data
* Data paper publication fees or other peer-reviewed research charges
====
