= Assessing goals and defining deliverables

== Learning objectives

[NOTE.objectives]
====
This module will review the overall objectives that your project will address.

After completing this module, you should be able to perform the following:

* Understand the overall processes that apply to data mobilization, from data digitization to data publishing through GBIF
* Understand the dataset classes supported by GBIF
* Understand the elements to consider when selecting the dataset classes, scope and structure of the datasets to be published through GBIF

====

== Module considerations

Continue to build upon the content of your concept note. If you have been selected to submit a full proposal, this means that the reviewers found merit in your concept note. Thus, it is important to build on it, considering the recommendations and feedback communicated by the evaluation panel. Update and expand any section as relevant.

Address the feedback you received on your concept note. This is a criterion of evaluation. The reviewers will expect that any identified issues or recommendations will be addressed in your full proposal. If you believe that is not feasible to address a specific feedback, then you should give a rationale explaining why.

Be brief and clear. Answer each section as clearly as possible and make sure you focus on the main message you want to convey and only add background or additional information if really needed and preferably through links to background documents and/or external resources.

* What will this project accomplish, both in terms of records published and increased capacity?
* What are the project’s expected deliverables?
* Why is the data mobilized by the project needed?
* Who will it benefit and how?
* Are there considerations regarding Indigenous data sovereignty and governance that relate to the data mobilization effort in the project?
* What are the time and staffing requirements for each activity? Does the plan align with the overall project duration?
* How will data mobilization activities be sustained into the future?

== Presentation

[NOTE.presentation]
This presentation 

&nbsp;

++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vSXUz6D1GnbQP5b6FWLusDpsdNGnu7fENUKqQxC0f3yoRgxPZOSQS9gPOiwqWm2Lg/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++

&nbsp;

== Activity

[NOTE.activity]
Quiz 