= Module 1: Goals assessment and deliverables

== Learning objectives

[NOTE.objectives]
====
This module will review the overall objectives that your project will address.

After completing this module, you should be able to perform the following:

* Understand the overall processes that apply to data mobilization, from data digitization to data publishing through GBIF
* Understand the dataset classes supported by GBIF
* Understand the elements to consider when selecting the dataset classes, scope and structure of the datasets to be published through GBIF

====

== Course Content and considerations

. What will this project accomplish, both in terms of records published and increased capacity?
. Why is this project needed?
. Who will it benefit and how?
. How long will it take to complete the project (will the project's activities continue after BID funding)? 
. How will the project activities be sustained into the future?
. What elements of the project are expected to continue after this funding is complete?
. What are the project’s expected deliverables?
. Are there any data sovereignty questions of indigenous and local communities when doing data mobilization?