= Organizing

== Video

[NOTE.presentation]
====
This video (15:52) focuses on tasks and the ways that they can be organized in order to prepare practical workable plans and clear documentation. 
If you are unable to watch the embedded video, you can link:../videos/Planning_Organizing.mp4[download^,opts=download] it locally. (MP4 - 26.2 MB)
====

[.responsive-video]
video::uhhK6B2VwIs[youtube]

== Video transcript

.Click to expand
[%collapsible]
====
//. {blank}
//+
[.float-group]
--
[.left]
&nbsp;

== Activity

[NOTE.activity]
====
For this activity, you will be using a virtual tabletop platform.
Review the exercise instructions below.
====

Using the stakeholder and goal analysis from exercise 1a, develop a workflow using the STAGE cards.

. Re-read the use case introduction, if necessary.
. Decide which TASKS for which each ROLE will be responsible.
. Review the STAGE cards and order the TASKS appropriately.
. Use the previously downloaded exercise sheet to provide your answers.

****
*Questions*   

* Are there obvious bottlenecks in the workflow?
For example: Are there too many tasks for a particular role/resource?
* What issues do you think would be important to the successful mobilization of data from the points of view of each stakeholder/role?
For example: What are the deliverables? Thinking about the general project timeframe, are they realistic?
* Consolidate notes and prioritize in order of importance.
* If you have time you can explore different combinations as different scenarios are possible in different contexts or even try to document the situation for your own project.
****