= Module 2: Resource analysis

== Learning objectives

[NOTE.objectives]
====
In this module, you will review key project planning stages and will learn how to create a viable workflow. 
Additionally, you will create an idealized project plan/workflow based on a USE CASE. 
You will identify goals, tasks, key stakeholders and roles and will assign specific tasks to stages.

After completing this module, you should be able to perform the following:

* Understand the different elements that are part of a biodiversity data mobilization plan
* Capacity to apply the different elements of a biodiversity data mobilization plan to a given institutional context
* Compose a clear planning document
* Estimate time and resources needed for proposed data mobilization activities
* Evaluate a biodiversity data mobilization plan

== Course content and considerations

. What organizations, institutions and communities are needed (for support, endorsement, human/technical/other resources, etc)?
.. What collaborations need to be built or strengthened?
. How much time and money is needed before, during and after the project?
. Who is responsible for each of the project goals and deliverables? 
.. When do they perform their roles?
.. What specific resources, skills and experience do they need to be successful?
.. What is the overall project timeline
.. Where are the project bottlenecks, areas in need of new or improved skills or additional resources?
.. How can the project mitigate risk?
. How will communication occur across the project, stakeholders, institutions and the community?