= Resourcing

== Video

[NOTE.presentation]
====
[NOTE.presentation]
In this video (15:09), you will learn how to define the elements that will have an impact on a project and will look at the interactions between the elements.
If you are unable to watch the embedded video, you can link:../videos/Planning_Resourcing.mp4[download^,opts=download] it locally. (MP4 - 25.1 MB)
====

[.responsive-video]
video::VRvUdMjd93c[youtube]

== Video transcript

.Click to expand
[%collapsible]
====
//. {blank}
//+
[.float-group]
--
[.left]
&nbsp;

== Activity

[NOTE.activity]
====
For this activity, you will be using a virtual tabletop platform.
Review the exercise instructions below.
====

Read USE CASE.

Using the cards select the goals that mostly closely match those the project outlines and then choose the tasks that would need to be carried out to complete them.
Next, identify the people/resources that the project has available to it and assign role cards to them as appropriate.
Lastly, assign these to their stakeholder groups and affiliations.

. Review the GOALS cards with the group, select and lay out the ones that fit the use case.
. Review the TASK cards with the group.
. Assign the TASK cards to each of the GOAL cards selected from the use case description.
. Identify the institutions and people mentioned in the use case text and make note of them.
. Lay out the AFFILIATIONS cards on the table.
. Review the STAKEHOLDER cards, identify any mentioned in the use case and then decide which AFFILIATION they belong to.
. Review the ROLE cards, identify any mentioned in the use case and decide which STAKEHOLDER group they belong to.
. Make notes to cards as appropriate.
. Once the cards are assigned take pictures/screenshots.
. Use the <<exercise-sheet,exercise sheet>> to provide your answers.

****
*Question*

Are there resources or goals missing from the cards that you feel are critical to the successful completion of the project? Note these on the answer sheet.
****