= Module 2 review

[NOTE.quiz]
====
Quiz yourself on the concepts learned in this section.

// Question 1
. What is the order of the five PMBoK Process Groupings?
+
[question, mc]
....

- [ ] Planning, Initiating, Monitoring and Controlling, Executing, Closing
- [x] Initiating, Planning, Executing, Monitoring and Controlling, Closing
- [ ] Initiating, Planning, Executing, Closing, Monitoring and Controlling
- [ ] Initiating, Planning, Monitoring and Controlling, Executing, Closing
....
// Question 2
. What are the types of deliverables? (multiple correct answers)
+
[question, mc]
....

- [x] Stated
- [x] Implied
- [ ] Estimated
- [x] Direct
- [x] Indirect
- [ ] Guesses
....
// Question 3
. What is a bottleneck?
+
[question, mc]
....

- [x] a blockage that delays development or progress
- [ ] a space where something or someone is missing
- [ ] a problem, or situation that prevents somebody from doing something, or that makes something impossible.
....
// Question 4
. Which are examples of mobilization tasks? (multiple correct answers)
+
[question, mc]
....

- [ ] Affiliation
- [x] Publishing
- [x] Imaging
- [x] Georeferencing
- [ ] Increased Public Awareness
....
====