= Course description

[NOTE.description]
====
This course aims to support the community maintaining the data in the Global Registry of Scientific Collections (GRSciColl). 
It gives an overview of the GRSciColl data structure and its relationship with GBIF data, explains the GRSciColl permissions system and presents the GRSciColl editing interface. 
By the end of the course, participants should be able to model and update the collection information in GRSciColl.

This course consists of videos and documentation paired with quizzes and practical exercises and the material of this course can be reused by the participants to organize their own online or onsite training events.

== Topics:

* Suggestion system, editing permissions and external sources
* Modelling information in GRSciColl
* How to edit GRSciColl content
====

== Audience

[NOTE.trainers]
====
This course is designed for individuals who wish to extensively contribute to managing the GRSciColl data content for a set of collections. 
The instruction provided is particularly useful for those who wish to become or are GRSciColl mediators for a country or set of countries.
====
  
== Prerequisites

[NOTE.prep]
====
* https://docs.gbif.org/course-introduction-to-gbif[Introduction to GBIF course^]

Additionally, individuals completing this course should possess the following skills and knowledge:

* A good command of English. While efforts are made to provide materials in other languages, instruction/videos will be in English.
====

== Certificate of completion

[NOTE.complete]
====
Upon successful attendance of live sessions and completion of activities, participants will receive a completion certification.
====
