= External sources: Synchronization with External sources

[NOTE]
====
You can access the content of this module in written or video format. If you are an audio-visual learner, you can skip the text and watch the video below.
====

[NOTE.presentation]
There will be a video presentation here

== Introduction

The GRSciColl institution and collection entries can have external primary sources of information that comes from another registry or website. Edits to such primary sources prompt updates to corresponding GRSciColl entries, eliminating the need to manage information across multiple registries.

Currently, the two possible sources of information for GRSciColl entries are https://sweetgum.nybg.org/science/ih/[Index Herbariorum] and the GBIF dataset and publisher metadata. Data for entries drawn from these sources should be edited at the source. In practice, GRSciColl’s editing interface doesn’t allow users to update fields that use information from an external source.

== Index Herbariorum

Every week, GRSciColl synchronizes with the https://sweetgum.nybg.org/science/ih/[Index Herbariorum] API, updating information for existing entries whose source is Index Herbariorum and creating suggestions for new entries as needed.

By default, one Index Herbariorum entry corresponds to an institution entry as well as a collection entry in GRSciColl because herbaria are often botanical collections within other institutions. You can read more about the rationale in this https://github.com/gbif/registry/issues/167[GitHub issue]. The synchronization process can generate duplicate institution entries when a single institution is home to several herbaria collections. This is why the synchronization now generates suggestions instead of creating new entries directly. Reviewers are asked to check the new entries suggested to make sure that no new duplicate is created.

[NOTE]
====
Editors can disconnect institutions entries from Index Herbariorum and choose to edit the institution directly in the GRSciColl editing interface.
====

== GBIF dataset metadata and GBIF publisher pages

The metadata of datasets published on GBIF can be used as primary sources for collection entries in GRSciColl. Unlike with the Index Herbariorum synchronization, there is no weekly schedule and new entries aren’t automatically created. Instead, editors must link GRSciColl collections to their sources manually. This is because the scope of GBIF includes data beyond the scope of GRSciColl. Note that there is also an option to create a collection entry from a dataset which is available to editors and mediators. When the metadata of a dataset is updated, the corresponding collection entry is updated immediately.
Similarly, the publisher information available on GBIF can be used as a primary source for institution entries in GRSciColl.



[NOTE.quiz]
====
For the following GRSciColl entry, find their master source.

// Link 1
. https://scientific-collections.gbif.org/collection/bc3d39fd-a7d4-4763-b951-2bdeddd8a5d2[This collection]
+
[question, mc]
....
- [ ] GBIF publisher: https://www.gbif.org/publisher/2cd829bb-b713-433d-99cf-64bef11e5b3e[see this link]
- [ ] GBIF dataset: https://www.gbif.org/dataset/b275a4c1-9859-4f3c-8ead-d86dde820fbc[see this link]
- [x] IH: http://sweetgum.nybg.org/science/ih/herbarium-details/?irn=125382[see this link]
....
// Link 2
. https://scientific-collections.gbif.org/institution/6a6ac6c5-1b8a-48db-91a2-f8661274ff80[This institution]
+
[question, mc]
....
- [x] GBIF publisher: https://www.gbif.org/publisher/2cd829bb-b713-433d-99cf-64bef11e5b3e[see this link]
- [ ] GBIF dataset: https://www.gbif.org/dataset/b275a4c1-9859-4f3c-8ead-d86dde820fbc[see this link]
- [ ] IH: http://sweetgum.nybg.org/science/ih/herbarium-details/?irn=125382[see this link]
....
// Link 3
. https://scientific-collections.gbif.org/collection/23fbece0-6e07-4a9c-ac86-7aa8e041ac9e[This collection]
+
[question, mc]
....
- [ ] GBIF publisher: https://www.gbif.org/publisher/2cd829bb-b713-433d-99cf-64bef11e5b3e[see this link]
- [x] GBIF dataset: https://www.gbif.org/dataset/b275a4c1-9859-4f3c-8ead-d86dde820fbc[see this link]
- [ ] IH: http://sweetgum.nybg.org/science/ih/herbarium-details/?irn=125382[see this link]
....

====
