= GRSciColl API - gets started


The GRSciColl API can allow you to edit or retrieve programmatically GRSciColl records. This API is part of the GBIF registry API and is documented here: https://techdocs.gbif.org/en/openapi/v1/registry#/Collections. All the functions available in the GRSciColl website and editing interface are also available in the API, including adding, editing and deleting records as well as making update suggestions. In addition to that, the permission system is the same in the web interface and the API.

The API also offers the possibility to upload and update records in bulk which is documented here: https://github.com/gbif/registry/blob/dev/docs/grscicoll_batches.md.

In order to use the GRSciColl API, you will need to use a client in the programming language of your choice. For example, you can use the `requests` library in Python or the `httr2` library in R. This will allow you to use any of the API functions available.
If you would like an entry level introduction to the GBIF APIs in general, you can watch https://www.gbif.org/composition/4TlmnRvvPs2RxrPvLH6mOa/data-use-club-practical-session-3-recording-and-resources[this recorded webinar] or read https://data-blog.gbif.org/post/gbif-api-beginners-guide/[this blogpost].

If you wish to edit the GRSciColl records programmatically by using the API, you will need to find and use the keys of the entries that you would like to edit.
For example, if you were to edit the entry for the New York Botanical Garden (https://scientific-collections.gbif.org/institution/ab83e5ab-f4f7-4c9b-a1d5-eb779dfb9377), you would have to use the UUID from its URL: `ab83e5ab-f4f7-4c9b-a1d5-eb779dfb9377`. This will allow you to tie the information to the correct entry (see also https://techdocs.gbif.org/en/openapi/v1/registry#/Institutions/updateInstitution).

If you maintain your own database or registry of collections and would like to push updates to GRSciColl, you can use the GRSciColl API. You just need to store the keys of the corresponding GRSciColl collection and institution entries on your side to ensure that the correct entries get updated.

In this module, we won’t go over the details of how the API can be used to update GRSciColl records. If you are thinking of making updates programmatically and you are unsure of how to proceed, please contact scientific-collections@gbif.org. We can help you write a script adapted to your needs.

[NOTE.quiz]
====
True or False?
****
// Question 1
. The GRSciColl API allows to create programmatically new entries in GRSciColl.
+
[question, mc]
....

- [x] True
- [ ] False
....

// Question 2
. The permission system is the same for the GRSciColl API and the GRSciColl editing interface.
+
[question, mc]
....

- [x] True
- [ ] False
....

// Question 3
. You can only use the GRSciColl API in the programming language Python.
+
[question, mc]
....

- [ ] True
- [x] False
....

// Question 4
. The UUID of this GRSciColl institution associated with the code NHMUK is d2a27206-87ab-47ea-b5fc-d2e57054b688
+
[question, mc]
....

- [ ] True
- [x] False
....
****
====
