[description]
= Course description

[NOTE.description]
====
This course provides an introduction to GBIF, the data available in GBIF's portal, accessing that data and information about engaging with GBIF and its community of practice.

Topics include:

* Information about GBIF
* GBIF-mediated data
* Data publishing
* Data access
* GBIF community of practice

This course is comprised of video and written instruction and paired with quizzes and practical exercises.
====

== Audience

[NOTE.trainers]
====
This course is designed for anyone who is interested in using data from or publishing data to GBIF. It is particularly useful for those who have a desire to know more about GBIF and its place in the biodiversity community and want to engage further with GBIF.
====

== Prerequisites

[NOTE.prep]
====
There are no prerequisites for this course.
This course serves as a prerequisite for other GBIF courses.
====

NOTE: While efforts are made to provide materials in other languages, videos will be in English. Efforts are made to include subtitles when possible.