= Acknowledgements 

The success of this course depends heavily on the support provided to participants from GBIF's network of capacity enhancement mentors. 
Visit the GBIF page on https://www.gbif.org/mentors[capacity enhancement mentoring^] to read more about these individuals and their contributions.

The course was first designed by an international group of node managers, with support from the GBIF Secretariat, as part of the Biodiversity Information for Development (BID) programme. https://www.gbif.org/programme/82243[BID^] is a multi-year programme funded by the European Union and led by the Global Biodiversity Information Facility (GBIF) with the aim of increasing the amount of biodiversity information available for use in scientific research and policymaking. 

The following individuals are recognized for their significant contributions to the course design, materials and instruction:

* Liam Lysaght (Ireland)*
* Fatima Parker-Allie (South Africa)*
* Anabela Plos (Argentina)*
* Raoufou Pierre Radji (Togo)*
* Carole Sinou (Canadensys)*
* Anders Telenius (Sweden)*
* Melianie Raymond (GBIF Secretariat)*
* Maheva Bagard Laursen (GBIF Secretariat)*
* Laura Russell (GBIF Secretariat)*

:figure-caption!:
.Meeting of the original trainers for this course, Copenhagen, 2019.

image::epn::Trainers.jfif[align=center,width=640,height=360]

*Originators of the curriculum
