= Final assignments

[NOTE.assignments]
====
For your final activities, you will complete and submit three exercises for evaluation.
====

== Exercise 1

*Prioritizing stakeholders*

Required files for submission:

* completed individual exercise sheet (MS Word Doc or similar is acceptable)

== Exercise 2

*Preparing a pitch*

Required files for submission:

* completed individual exercise sheet (MS Word Doc or similar is acceptable)
* group recording (only one person from the group needs to upload the recording)

== Exercise 3

*Scoping a Participant node*

Required files for submission:

* completed individual exercise sheet (MS Word Doc or similar is acceptable)

IMPORTANT: *All files must be submitted in English*. Include the assignment name and exercise number along with your name and group on all files submitted.  
For example:

* Orange-Russell-Exercise1.docx
* Orange-Russell-Exercise2.docx
* Orange-Exercise2-recording.zip (please compress the mp4 file)
* Orange-Russell-Exercise3.docx

Contact training@gbif.org if you have any questions.

== Assignment submission

// Create a Box submission form and replace with appropriate link

ifdef::backend-pdf[]
Assignments can be submitted from the online (HTML) version of the course.
endif::backend-pdf[]

ifndef::backend-pdf[]
Please submit your assignment files using the form below.  If you do not see a form, you can also visit the https://gbif.app.box.com/f/8435157e5a574b5487b5ef087f575328:[submission site^] in a new window.

++++
<iframe src="https://gbif.app.box.com/f/8435157e5a574b5487b5ef087f575328" style="width: 100%; min-height: 900px;"></iframe>
++++
endif::backend-pdf[]
