= Final assignments

[NOTE.assignments]
====
For your final activities, you will complete and submit three exercises for evaluation.
====

== Exercise 1

*Prioritizing stakeholders*

Required files for submission:

* completed individual exercise sheet (MS Word Doc or similar is acceptable)

== Exercise 2

*Preparing a pitch*

Required files for submission:

* completed individual exercise sheet (MS Word Doc or similar is acceptable)
* group recording (only one person from the group needs to upload the recording)

== Exercise 3

*Scoping a Participant node*

Required files for submission:

* completed individual exercise sheet (MS Word Doc or similar is acceptable)

== Assignment submission

****
Please *submit your assignment files using the form below*.  If you do not see a form, you can also visit the https://gbif.app.box.com/f/8435157e5a574b5487b5ef087f575328:[submission site^] in a new window.

IMPORTANT: *All files must be submitted in English*. Include your group number, your surname and the exercise number on all files submitted.  

For example:

* Group1-Russell-Exercise1.docx
* Group1-Russell-Exercise2.docx
* Group1-Exercise2-recording.zip (please compress the mp4 file)
* Group1-Russell-Exercise3.docx

Contact training@gbif.org if you have any questions.
****

// Create a Box submission form and replace with appropriate link

ifdef::backend-pdf[]
Assignments can be submitted from the online (HTML) version of the course.
endif::backend-pdf[]

ifndef::backend-pdf[]

&nbsp; 

++++
<iframe src="https://gbif.app.box.com/f/8435157e5a574b5487b5ef087f575328" style="width: 100%; min-height: 900px;"></iframe>
++++
endif::backend-pdf[]
