= Course description

****
This course aims to support teams working on GBIF funded projects, observers and other interested participants in the first stages of building a case for formal Participation in GBIF and establishing a Participant node. 

Topics include:

* Benefits of GBIF Participation and of establishing a Participant Node
* Process for joining GBIF
* Key audiences to engage in GBIF at a national level
* Participatory approach to establishing a Participant node
* Ongoing support towards formal GBIF Participation and for establishing nodes

This course is comprised of videos and documentation paired with quizzes and practical exercises. 
Course participants will be placed into peer groups and social interaction is encouraged. 
Completing the practical exercises, providing peer feedback within your group, and attending two live question and answer sessions are compulsory to successfully completing the course and receiving certification.

At the time of registration, all participants must commit to completing the course within the allocated time-frame and to supporting peers in the group work.
****

== Audience

This course is aimed at interested individuals and teams engaged in GBIF’s capacity development programmes based in countries or organizations that are not yet formal GBIF Participants. Encouraging national Participation and the establishment of a Participant node brings many benefits and is a good way to ensure the sustainability of efforts started through capacity development projects focused on biodiversity data mobilization and use.

== Prerequisites

* https://docs.gbif.org/course-introduction-to-gbif[Introduction to GBIF course^]

== Learning objective

Participants that complete this course are empowered to make the case for establishing nodes - and biodiversity information facilities more generally - for the sustainability of biodiversity data mobilization and use activities. 

// inlude if needed, otherwise remove
== Certificate of completion

Upon successful submission of exercises, attendance of live sessions, and interaction with peer groups, participants have the opportunity to receive a completion certification.
