= Files for download

All files for the course may be downloaded from this page. 
Or if you prefer, all files are linked individually throughout the course as they occur in the curriculum. 
The video files are embedded throughout the course, as well, and play from YouTube or Vimeo. Subtitles are available when playing from YouTube and Vimeo for most videos. 
If you have difficulty accessing the embedded videos, please download the mp4 files to play them locally on your computer.

== Videos

The videos are narrated in English. Subtitles are not available for the downloaded videos.

xref:attachment$welcome_to_the_epn_course.zip[Welcome to the Course] (33.9 MB)

xref:attachment$gbif_and_policy.zip[GBIF and policy] (66.5 MB)

xref:attachment$ValueOfGBIFVideos.zip[Value of GBIF] (81.2 MB)

xref:attachment$Speed-dating_GNM2021.pdf[Slides from the session]


== Exercise sheets

There are four exercise sheets for this course. 
They are Microsoft Word documents. 
The exercises sheets are written in English and should be completed in English.

* The first is for keeping track of your answers to the self-study activities in the section on Building a case for engagement in GBIF. You are welcome to discuss your answers with your group and during the live sessions. 

** xref:attachment$A-Self_Study_Note_Sheet.docx[Download the self-study note sheet] (MS Word 62 KB)

* The next three correspond to the practical exercises that you will complete in the section on Engaging stakeholders towards establishing a node. You will need to submit these to your peer-learning group to receive the certificate of completion for the course.

** xref:attachment$B-Exercise-1-Exercise-sheet-EN.docx[Download the activity sheet for Exercise 1] (MS Word 69 KB)

** xref:attachment$C-Exercise-2-Exercise-sheet-EN.docx[Download the activity sheet for Exercise 2] (MS Word 58 KB)

** xref:attachment$D-Exercise-3-Exercise-sheet-EN.docx[Download the activity sheet for Exercise 3] (MS Word 60 KB)

== Action plan

A Microsoft Word document to be used post-course.
The action plan is written in English and should be completed in English if feedback is requested.

xref:attachment$ActionPlanTowardsGBIFParticipation.docx[Download the action plan] (MS Word 73.3 KB)
