= Understanding GBIF's relevance

The starting point for building a case for a country or international organization to formally participate in GBIF is to understand how GBIF is relevant. In this section, we explore GBIF’s relevance through videos guiding you to consider how best to communicate the benefits GBIF brings to its participants.

== GBIF's relevance to policy frameworks

[NOTE.presentation]
====
In this video (14:53), GBIF Deputy Director, Tim Hirsch, explains GBIF's relevance for science and policy. 
If you are unable to watch the embedded Vimeo video, you can download it locally from the xref:downloads.adoc[Files for download] page.

[.responsive-video]
video::891020660[vimeo]
====

== GBIF's relevance in thematic areas

[NOTE.presentation]
====
In these six videos (<15:00) you will learn about the value of GBIF to different thematic areas. 
If you are unable to watch via the embedded Vimeo showcase, you can download the videos locally from the xref:downloads.adoc[Files for download] page.

ifdef::backend-pdf[]
The presentation can be viewed in the online version of the course.
endif::backend-pdf[]

ifndef::backend-pdf[]
++++
<div style='padding:56.25% 0 0 0;position:relative;'><iframe src='https://vimeo.com/showcase/9461923/embed' allowfullscreen frameborder='0' style='position:absolute;top:0;left:0;width:100%;height:100%;'></iframe></div>
++++
endif::backend-pdf[]
====

== Consider your own country or organization

[NOTE.activity]
====
After watching the videos in this section, use your notes sheet to list at least five rationale statements for why GBIF is of relevance to its Participants. 
====
