= Understanding GBIF's value

The starting point for building a case for a country or international organization to formally participate in GBIF is to understand the value of GBIF as data infrastructure and an international network. 
In this section, we explore GBIF’s value and relevance through reports and videos guiding you to consider how best to communicate the benefits GBIF brings to its participants.

== Economic valuation

The 2023 report, Economic valuation and assessment of the impact of the GBIF network, prepared and published by Deloitte Access Economics, gives insight into the value that GBIF provides to its users and in broader societal benefits. 

[NOTE.documentation]
====
The news item that accompanied the release of this report points to highlights, but we recommend that you also review the full report for a more complete understanding.

* https://www.gbif.org/news/5WZThcL928vmPnSvrGhZfE/report-reveals-return-on-investments-in-gbif[News item^] 
* https://www.deloitte.com/au/en/services/economics/perspectives/total-economic-value-open-access-database-living-world.html[Full report^] 
====

[NOTE.presentation]
====
In this video (6:55) Kyle Copas, GBIF Communications Manager, unpacks some of the key expressions of value from the Deloitte Access Economics report and explains how to estimate the national value of time savings from GBIF-enabled research.

[.responsive-video]
video::865685244[vimeo]
====

== GBIF's relevance to policy frameworks

[NOTE.presentation]
====
In this video (10:08) from the GBIF Impact and Action Symposium, 2021, GBIF's Executive Secretary, Dr. Joe Miller, discusses GBIF's relevance for science and policy. 
If you are unable to watch the embedded Vimeo video, you can link:../videos/Dr_Joe_Miller_GBIF.zip[download,opts=download] it locally.

[.responsive-video]
video::656603612[vimeo]
====

== Thematic areas

[NOTE.presentation]
====
In these six videos (<15:00) you will learn about the value of GBIF to different thematic areas. 
If you are unable to watch via the embedded Vimeo showcase, the videos can be link:../videos/ValueOfGBIFVideos.zip[downloaded,opts=download] locally.

ifdef::backend-pdf[]
The presentation can be viewed in the online version of the course.
endif::backend-pdf[]

ifndef::backend-pdf[]
++++
<div style='padding:56.25% 0 0 0;position:relative;'><iframe src='https://vimeo.com/showcase/9461923/embed' allowfullscreen frameborder='0' style='position:absolute;top:0;left:0;width:100%;height:100%;'></iframe></div>
++++
endif::backend-pdf[]
====

== Activity

[NOTE.activity]
====
After watching the videos in this section, keep note in your activity sheet of at least five rationale statements for why GBIF is of value to its Participants. 
====
